### ISSUE TITLE
Solução dos problemas 1026-1050

### ISSUE THREAD

**Issue by lrlucena** [potigol/URI-Potigol#9]
Solução dos problemas do URI Online Judge

- [ ] 1026
- [ ] 1027
- [ ] 1028
- [ ] 1029
- [ ] 1030
- [ ] 1031
- [ ] 1032
- [ ] 1033
- [ ] 1034
- [x] 1035
- [x] 1036
- [x] 1037
- [x] 1038
- [ ] 1039
- [x] 1040
- [x] 1041
- [x] 1042
- [x] 1043
- [x] 1044
- [ ] 1045
- [x] 1046
- [ ] 1047
- [x] 1048
- [ ] 1049
- [x] 1050

**Comment by Marcos314** [comment]
Boa noite, vou tentar fazer esse ok?!

**Comment by lrlucena** [comment]
Ótimo, fique a vontade. Pode ir enviando à medida que for fazendo.

**Comment by lrlucena** [comment]
Fechando para abrir novos issues por categoria.
